POST http://localhost:8080/api/usuario/cadastrar
Content-Type: application/json
Accept: */*

{
        "nome": "Leonard Karic",
        "email": "leonardkaric@gmail.com",
        "senha": "20042004",
        "telefone": "11965823342"
}
